imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*, htdocs/*]

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    tests-and-coverage:
      nodes:
          my-tests:
              environment:
                  php:
                      version: 7.4
      tests:
          override:
              -
                  command: "make phpunit"
                  coverage:
                      file: "build/coverage.clover"
                      format: "php-clover"
